### ISSUE TITLE
UI and UX enhancements

### ISSUE THREAD

**Issue by AGSadovsky** [ibagroup-eu/Visual-Flow#1]
Enhance front end and user experience:

- Hide sensitive fields data on Connection preview window;
- Show "empty calendar" icon for disabled cron;
- Implement zoom out down to 20%;
- Redesign jobs modal window for pipelines designer;
- Cache "status", "last run" for jobs/pipelines;
- The same parameter values shouldn't be considered as duplicates (only keys);
- Fix incorrect links order for the "left join";
- Fix incorrect display of jobs time status;
- Fix incorrect display of the Truncate mode label.

**Comment by UladzislauKhizhanok** [comment]
All the features have been implemented in the release v0.9.20:
https://github.com/ibagroup-eu/Visual-Flow/releases/tag/v0.9.20

**Comment by AGSadovsky** [comment]
Well done!
