### ISSUE TITLE
Integrate with existing spark cluster

### ISSUE THREAD

**Issue by danhoduc** [ibagroup-eu/Visual-Flow#3]
I deployed spark standalone cluster and it worked well
How can I connect Visual Flow to the existing spark cluster for computing?

**Comment by mhaurylenka-ibagroup-eu** [comment]
@danhoduc Hello. It is possible to specify the desired master path to the spark cluster through the Visual-Flow-backend configuration. 
See https://github.com/ibagroup-eu/Visual-Flow-backend/blob/main/src/main/resources/application.yaml.example#L73 line - master property, `https://kubernetes.default.svc` by default, but you can specify it using existing spark cluster in this way `k8s://https://<k8s-host>:<k8s-port>` (or `spark://<host>:<port>`)

**Comment by AGSadovsky** [comment]
@danhoduc, feel free to open more questions/issues to our team or refer to our official web site https://visual-flow.com/ for more information.
